### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by drsagitn** [isl-org/DirectFuturePrediction#7]
I tried to run the D3_battle example but got following error about "list index out of range"

`thinh@thinh-H67MU3:~/drl/DirectFuturePrediction/examples/D3_battle$ python3 run_exp.py 
/usr/local/lib/python3.5/dist-packages/vizdoom/vizdoom.so
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
Requested resolution not supported: <class 'AttributeError'> . Setting to 160x120 and resizing
2017-10-11 16:26:37.844556: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 16:26:37.844600: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-11 16:26:38.117708: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-10-11 16:26:38.118064: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: GeForce GTX 1060 3GB
major: 6 minor: 1 memoryClockRate (GHz) 1.759
pciBusID 0000:01:00.0
Total memory: 2.93GiB
Free memory: 2.15GiB
2017-10-11 16:26:38.118356: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-11 16:26:38.118416: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-11 16:26:38.118476: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0)
/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gradients_impl.py:95: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
Traceback (most recent call last):
  File "run_exp.py", line 131, in <module>
    main(sys.argv[1:])
  File "run_exp.py", line 126, in main
    experiment.run(main_args[0])
IndexError: list index out of range
`

Is it because of the resolution not supported from vizdoom?

**Comment by drsagitn** [comment]
Sorry, my bad.I ran with missing param
